/**
 * Tests for the extracted OcrImagePreprocess module.
 *
 * Locks the sharp pipeline as a stable seam:
 *  - applies EXIF rotate() so phone-sideways images are uprighted
 *    BEFORE thresholding (the CR-#436 F1 fix)
 *  - upscales small images above MIN_WIDTH_PX (1500) so tesseract
 *    has enough pixels per Hebrew glyph
 *  - applies greyscale + binary threshold so the output is a
 *    1-channel high-contrast PNG ready for tesseract.js
 *
 * Uses a small synthetic PNG generated by sharp itself so the
 * tests run on every platform without committed binary fixtures.
 */

import sharp from 'sharp';
import { describe, expect, it } from 'vitest';

import preprocessForOcr from '../../../src/Services/Receipt/OcrImagePreprocess.js';

const SMALL_WIDTH = 200;
const SMALL_HEIGHT = 100;
const LARGE_WIDTH = 1800;
const LARGE_HEIGHT = 900;
const MIN_OUTPUT_WIDTH = 1500;
// Dims chosen so both width AND height exceed MIN_OUTPUT_WIDTH (1500),
// which keeps the F1 rotate-regression test free of any resize side
// effects — the ONLY transformation that should affect output dims is
// the .rotate() call swapping axes for EXIF orientation 6.
const ORIENTED_WIDTH = 2000;
const ORIENTED_HEIGHT = 1800;

async function buildSyntheticImage(width: number, height: number): Promise<Buffer> {
  return await sharp({
    create: {
      width,
      height,
      channels: 3,
      background: { r: 240, g: 240, b: 240 },
    },
  })
    .png()
    .toBuffer();
}

async function buildOrientedJpeg(width: number, height: number, orientation: number): Promise<Buffer> {
  // EXIF tags are only persisted by sharp in JPEG output; PNG loses
  // the orientation tag and would defeat the purpose of this fixture.
  return await sharp({
    create: {
      width,
      height,
      channels: 3,
      background: { r: 240, g: 240, b: 240 },
    },
  })
    .withMetadata({ orientation })
    .jpeg()
    .toBuffer();
}

describe('OcrImagePreprocess — preprocessForOcr', () => {
  it('upscales small images above the MIN_WIDTH_PX threshold', async () => {
    const input = await buildSyntheticImage(SMALL_WIDTH, SMALL_HEIGHT);
    const output = await preprocessForOcr(input);
    const meta = await sharp(output).metadata();
    expect(meta.width ?? 0).toBeGreaterThanOrEqual(MIN_OUTPUT_WIDTH);
  });

  it('leaves already-large images at their native width', async () => {
    const input = await buildSyntheticImage(LARGE_WIDTH, LARGE_HEIGHT);
    const output = await preprocessForOcr(input);
    const meta = await sharp(output).metadata();
    expect(meta.width).toBe(LARGE_WIDTH);
  });

  it('emits a PNG output (greyscale + threshold pipeline ran)', async () => {
    const input = await buildSyntheticImage(LARGE_WIDTH, LARGE_HEIGHT);
    const output = await preprocessForOcr(input);
    const meta = await sharp(output).metadata();
    expect(meta.format).toBe('png');
  });

  it('applies EXIF .rotate() so orientation=6 photos have axes swapped', async () => {
    // Orientation 6 = "rotate 90° CW" — raw pixel dims 2000x1800 must
    // become 1800x2000 after .rotate(). If a future regression drops
    // .rotate() from the pipeline, this assertion fails because the
    // output dims would remain 2000x1800 (unswapped).
    const input = await buildOrientedJpeg(ORIENTED_WIDTH, ORIENTED_HEIGHT, 6);
    const output = await preprocessForOcr(input);
    const meta = await sharp(output).metadata();
    expect(meta.width).toBe(ORIENTED_HEIGHT);
    expect(meta.height).toBe(ORIENTED_WIDTH);
  });

  it('returns a non-empty PNG buffer for a small input', async () => {
    const input = await buildSyntheticImage(SMALL_WIDTH, SMALL_HEIGHT);
    const output = await preprocessForOcr(input);
    expect(Buffer.isBuffer(output)).toBe(true);
    expect(output.length).toBeGreaterThan(0);
  });
});
